coverage:
  paths:
    - coverage/.resultset.json
testExecutionTime:
  steps:
    - Exec MiniTest
codeToTestRatio:
  test:
   - "mini_test/*.rb"
   - "mini_unit/*.rb"
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/base
