coverage:
 paths:
   - coverage/.resultset.json
testExecutionTime:
 steps:
   - Exec MiniTest
  acceptable: current <= 3min && diff <= 1min
codeToTestRatio:
 test:
   - "mini_test/*.rb"
   - "mini_unit/*.rb"
comment:
 if: is_pull_request
 hideFooterLink: false
report:
 datastores:
   - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/base
