coverage:
 paths:
   - coverage/.resultset.json
   acceptable: current >= 0%
   # acceptable: current >= 60% && diff >= 0%
testExecutionTime:
 steps:
   - Exec MiniTest
  acceptable: current <= 3min && diff <= 1min
codeToTestRatio:
 test:
   - "mini_test/*.rb"
   - "mini_unit/*.rb"
   acceptable: current >= 0.1
   #acceptable: current >= 1.2 && diff >= 0
comment:
 if: is_pull_request
 hideFooterLink: false
report:
 datastores:
   - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/base
